project:
  type: book

execute:
  freeze: auto

book:
  page-navigation: true
  title: "Dokumentation"
  description: "AppName Dokumentation"
  site-url: "https://HdM-LLM.github.io/docs"
  repo-url: https://github.com/HdM-LLM/docs
  repo-actions: [edit, issue, source]
  open-graph: true
  image: "/images/logo.png"
  favicon: "/images/logo.png"
  search: true
  page-footer:
    left: |
      © Team 03, 2023
    center:
      - text: "Übersicht"
        href: index.qmd
      - text: "Einleitung"
        href: einleitung.qmd
    right:
      - icon: person-circle
      - text: "Moodle"
        # href: https://moodle.hdm-stuttgart.de/login/index.php # causes error
        aria-label: Moodle
  chapters:
    - index.qmd
    - einleitung.qmd
    - grundlagen.qmd
    - ziele_und_anforderungen.qmd
    - design_und_entwicklung.qmd
    - evaluation.qmd
    - referenzen.qmd

format:
  html:
    toc: true
    theme: sandstone
    code-copy: true
    code-overflow: wrap

bibliography: references.bib
