project:
  type: book

execute:
  freeze: auto

book:
  page-navigation: true
  title: "SkillSync"
  description: "Documentation"
  site-url: "https://HdM-LLM.github.io/docs"
  repo-url: https://github.com/HdM-LLM/docs
  repo-actions: [edit, issue, source]
  open-graph: true
  image: "/images/logo.png"
  favicon: "/images/logo.png"
  search: true
  page-footer:
    left: |
      © Team 03, 2023-2024
    center:
      - text: "Overview"
        href: index.qmd
    right:
      - icon: person-circle
      - text: "Moodle"
        # href: https://moodle.hdm-stuttgart.de/login/index.php # causes error
        aria-label: Moodle
  chapters:
    - index.qmd
    - introduction.qmd
    - use_case.qmd
    - design_decisions.qmd
    - implementation.qmd
    - user_instructions.qmd
    - future_road_map.qmd
    - references.qmd

format:
  html:
    toc: true
    theme: sandstone
    code-copy: true
    code-overflow: wrap

bibliography: references.bib
