# Goal and Requirements

Our main goal is to create a simple and easy to use tool for human resource managers to manage their applications and vacancies. The tool should be able to handle the following tasks:

- Create new job postings
- Manage applications
- Manage applicants
- Manage job postings

## Job Posting

A job posting or vancancy is a description of a job opening. It contains information about the job, such as the job title, the job description, the job qualifications, the job type (full-time, part-time, etc.), the job category (e.g. IT, Marketing, etc.), the salary, the job requirements, aswell as the job benefits.

## Application

An application is a document which generally consists of a cover letter, a resume, and other supporting materials. It is used by applicants to apply for a job posting.

## Applicant

An applicant is a person who applies for a job posting. An applicant can have multiple applications to different job postings.

# Use Cases

## Create a new job posting

An employee of the company should be able to create a new job posting. The job posting should contain the following information:

- Job title
- Job description
- Job qualifications
- Job type
- department
  
## Manage applications

An employee in HR of the company should be able to manage applications. This includes the following tasks:

- View applications
- Delete applications
- Update applications
- Create applications
- Filter applications

## Manage applicants

An employee in HR of the company should be able to manage applicants. This includes the following tasks:

- View applicants
- Delete applicants
- Update applicants
- Create applicants
- Filter applicants
- View applications of an applicant

